In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Load the dataset
data = pd.read_csv(r'D:\price_revalue_stystem\data\02-preprocessed\cars_24_processed.csv')
df=data.copy()

In [19]:
df.head()

,Year,Distance,Owner,Fuel,Drive,Type,Price,brand,model,State,Price_log
0,2022.0,3878,1,Petrol,Manual,HatchBack,514000,Maruti,S,Haryana,13.149980
1,2018.0,32041,1,Petrol,Manual,Sedan,674000,Hyundai,XCENT,Tamil Nadu,13.420987
2,2021.0,96339,1,Diesel,Automatic,SUV,1952000,Tata,SAFARI,Telangana,14.484366
3,2019.0,51718,1,Diesel,Manual,SUV,690000,Maruti,VITARA,West Bengal,13.444448
4,2021.0,19811,1,Petrol,Manual,HatchBack,526000,Tata,TIAGO,Haryana,13.173058

In [20]:
df["age_of_car"] = 2026 - df["Year"]

In [21]:
df.head()

,Year,Distance,Owner,Fuel,Drive,Type,Price,brand,model,State,Price_log,age_of_car
0,2022.0,3878,1,Petrol,Manual,HatchBack,514000,Maruti,S,Haryana,13.149980,4.0
1,2018.0,32041,1,Petrol,Manual,Sedan,674000,Hyundai,XCENT,Tamil Nadu,13.420987,8.0
2,2021.0,96339,1,Diesel,Automatic,SUV,1952000,Tata,SAFARI,Telangana,14.484366,5.0
3,2019.0,51718,1,Diesel,Manual,SUV,690000,Maruti,VITARA,West Bengal,13.444448,7.0
4,2021.0,19811,1,Petrol,Manual,HatchBack,526000,Tata,TIAGO,Haryana,13.173058,5.0

In [22]:
df["brand"].unique()

array(['Maruti', 'Hyundai', 'Tata', 'Renault', 'Honda', 'Ford', 'Datsun',
       'Toyota', 'Mahindra', 'Nissan', 'KIA', 'Volkswagen', 'Skoda',
       'BMW', 'Jeep', 'MG'], dtype=object)

In [23]:
df["age_of_car"].unique()

array([ 4.,  8.,  5.,  7.,  9., 11., 14., 10., 16., 15., 13., 12.,  6.,
        3.])

In [24]:
x=df.drop(columns=["Price","Price_log"])
y=df["Price_log"]

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train1,x_test1,y_train1,y_test1=train_test_split(x,y1,test_size=0.2,random_state=42)

In [26]:
def feature_engineering(df):
    
    df = df.copy()
    
    df['age_of_car'] = 2026 - df['Year']
    df['km_per_year'] = df['Distance'] / (df['age_of_car'] + 1)
    df['age_x_distance'] = df['age_of_car'] * df['Distance']
    
    df['brand'] = df['brand'].str.upper().str.strip()
    df['model'] = df['model'].str.upper().str.strip()
    
    df['brand_count'] = df['brand'].map(df['brand'].value_counts())
    df['model_count'] = df['model'].map(df['model'].value_counts())
    
    df['is_luxury'] = df['brand'].isin(['BMW', 'JEEP']).astype(int)
    
    return df

x_train = feature_engineering(x_train)
x_test  = feature_engineering(x_test)

In [27]:
x_train.head()

,Year,Distance,Owner,Fuel,Drive,Type,brand,model,State,age_of_car,km_per_year,age_x_distance,brand_count,model_count,is_luxury
6782,2017.0,58647,1,Petrol,Manual,HatchBack,MARUTI,ALTO,Telangana,9.0,5864.700000,527823.0,2689,416,0
2317,2015.0,79288,1,Petrol,Automatic,Sedan,VOLKSWAGEN,VENTO,Maharashtra,11.0,6607.333333,872168.0,131,40,0
5318,2022.0,7396,1,Petrol,Manual,HatchBack,MARUTI,SWIFT,Tamil Nadu,4.0,1479.200000,29584.0,2689,620,0
904,2020.0,22814,2,Petrol,Manual,SUV,HYUNDAI,VENUE,Karnataka,6.0,3259.142857,136884.0,1559,57,0
1446,2017.0,28696,1,Petrol,Manual,HatchBack,HYUNDAI,ELITE,Maharashtra,9.0,2869.600000,258264.0,1559,301,0

In [28]:
x_train.head()

,Year,Distance,Owner,Fuel,Drive,Type,brand,model,State,age_of_car,km_per_year,age_x_distance,brand_count,model_count,is_luxury
6782,2017.0,58647,1,Petrol,Manual,HatchBack,MARUTI,ALTO,Telangana,9.0,5864.700000,527823.0,2689,416,0
2317,2015.0,79288,1,Petrol,Automatic,Sedan,VOLKSWAGEN,VENTO,Maharashtra,11.0,6607.333333,872168.0,131,40,0
5318,2022.0,7396,1,Petrol,Manual,HatchBack,MARUTI,SWIFT,Tamil Nadu,4.0,1479.200000,29584.0,2689,620,0
904,2020.0,22814,2,Petrol,Manual,SUV,HYUNDAI,VENUE,Karnataka,6.0,3259.142857,136884.0,1559,57,0
1446,2017.0,28696,1,Petrol,Manual,HatchBack,HYUNDAI,ELITE,Maharashtra,9.0,2869.600000,258264.0,1559,301,0

In [29]:
x_train1 = feature_engineering(x_train1)
x_test1  = feature_engineering(x_test1)

# Encoding

In [30]:
def encode_categorical(x_train, x_test, categorical_cols):

    encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')


    encoder.fit(x_train[categorical_cols])

  
    train_encoded = encoder.transform(x_train[categorical_cols])
    train_encoded_df = pd.DataFrame(
        train_encoded,
        columns=encoder.get_feature_names_out(categorical_cols),
        index=x_train.index
    )

    
    test_encoded = encoder.transform(x_test[categorical_cols])
    test_encoded_df = pd.DataFrame(
        test_encoded,
        columns=encoder.get_feature_names_out(categorical_cols),
        index=x_test.index
    )

   

    
    x_train = pd.concat([x_train, train_encoded_df], axis=1)
    x_test = pd.concat([x_test, test_encoded_df], axis=1)

    return x_train, x_test
cols = ['Drive', 'Type', 'Fuel']
x_train, x_test = encode_categorical(x_train, x_test, cols)

In [31]:
x_train.head()

,Year,Distance,Owner,Fuel,Drive,Type,brand,model,State,age_of_car,...,Drive_Manual,Type_HatchBack,Type_Lux_SUV,Type_Lux_sedan,Type_SUV,Type_Sedan,Fuel_Cng,Fuel_Diesel,Fuel_Lpg,Fuel_Petrol
6782,2017.0,58647,1,Petrol,Manual,HatchBack,MARUTI,ALTO,Telangana,9.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2317,2015.0,79288,1,Petrol,Automatic,Sedan,VOLKSWAGEN,VENTO,Maharashtra,11.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
5318,2022.0,7396,1,Petrol,Manual,HatchBack,MARUTI,SWIFT,Tamil Nadu,4.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
904,2020.0,22814,2,Petrol,Manual,SUV,HYUNDAI,VENUE,Karnataka,6.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1446,2017.0,28696,1,Petrol,Manual,HatchBack,HYUNDAI,ELITE,Maharashtra,9.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [32]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6240 entries, 6782 to 7270
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             6240 non-null   float64
 1   Distance         6240 non-null   int64
 2   Owner            6240 non-null   int64
 3   Fuel             6240 non-null   object
 4   Drive            6240 non-null   object
 5   Type             6240 non-null   object
 6   brand            6240 non-null   object
 7   model            6240 non-null   object
 8   State            6240 non-null   object
 9   age_of_car       6240 non-null   float64
 10  km_per_year      6240 non-null   float64
 11  age_x_distance   6240 non-null   float64
 12  brand_count      6240 non-null   int64
 13  model_count      6240 non-null   int64
 14  is_luxury        6240 non-null   int64
 15  Drive_Automatic  6240 non-null   float64
 16  Drive_Manual     6240 non-null   float64
 17  Type_HatchBack   6240 non-null   float64
 18  Type_Lux_SUV     6240 non-null   float64
 19  Type_Lux_sedan   6240 non-null   float64
 20  Type_SUV         6240 non-null   float64
 21  Type_Sedan       6240 non-null   float64
 22  Fuel_Cng         6240 non-null   float64
 23  Fuel_Diesel      6240 non-null   float64
 24  Fuel_Lpg         6240 non-null   float64
 25  Fuel_Petrol      6240 non-null   float64
dtypes: float64(15), int64(5), object(6)
memory usage: 1.3+ MB

In [33]:
train_df = pd.concat([x_train, y_train], axis=1)
test_df = pd.concat([x_test, y_test], axis=1)

In [34]:
train_df.to_csv(r'D:\price_revalue_stystem\data\03-features\train_df.csv', index=False)
test_df.to_csv(r'D:\price_revalue_stystem\data\03-features\test_df.csv', index=False)